services:
  example-function-app1:
    image: ${FUNCTION_APP1_IMAGE}
    platform: linux/amd64
    ports:
      - "${FUNCTION_APP1_HTTP_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENVIRONMENT:-production}
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - OTEL_SERVICE_NAME=${FUNCTION_APP1_OLTP_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=x-otlp-api-key=${ASPIRE_DASHBOARD_OTLP_PRIMARYAPIKEY}
      - FUNCTIONS_EXTENSION_VERSION=~4
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    depends_on:
      - azurite
    networks:
      - my_func_net
