services:
  httpapi:
    image: ${HTTPAPI_IMAGE}
    ports:
      - "${HTTPAPI_HTTP_PORT}:8080"
      - "${HTTPAPI_HTTPS_PORT}:8081"
    volumes:
      - ${HTTPS_CERT_PATH}/${HTTPS_CERT_NAME_KEY}:/usr/local/share/ssl/${HTTPS_CERT_NAME_KEY}:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENVIRONMENT:-production}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/${HTTPS_CERT_NAME_CRT}
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/usr/local/share/ssl/${HTTPS_CERT_NAME_KEY}
    networks:
      - my_func_net
